// This file was @generated by ip_geo/geo using location 0.9.16 and Wikidata at 2024-08-05T21:32:19Z. Do not edit!

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Copyright © 2024 RemasteredArch
//
// This file is part of ip_geo.
//
// ip_geo is free software: you can redistribute it and/or modify it under the terms of the GNU
// Affero General Public License as published by the Free Software Foundation, either version 3 of
// the License, or (at your option) any later version.
//
// ip_geo is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
// even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License along with ip_geo. If
// not, see <https://www.gnu.org/licenses/>.

use std::{collections::HashMap, sync::Arc};

/// Represents a country or other geographic region.
#[derive(Clone, Debug)]
pub struct Country {
    /// The full name of the country.
    ///
    /// Ex. "Belgium".
    pub name: Arc<str>,
    /// The two letter country code.
    ///
    /// Ex. "BE" for Belgium.
    pub code: Arc<str>,
    /// The coordinates of the center of the country.
    ///
    /// Ex. `(4.668055555, 50.641111111)`.
    pub coordinates: (f64, f64),
}

/// A map of countries, with the ISO 3166-1 alpha-2 code as the key.
#[rustfmt::skip]
pub fn get_countries() -> HashMap<Arc<str>, Country> {HashMap::from([
    {let c_ad = Country {
        name: "Andorra".into(),
        code: "AD".into(),
        coordinates: (1.555277777, 42.558333333),
    }; (c_ad.code.clone(), c_ad)},

    {let c_ae = Country {
        name: "United Arab Emirates".into(),
        code: "AE".into(),
        coordinates: (54.3, 24.4),
    }; (c_ae.code.clone(), c_ae)},

    {let c_af = Country {
        name: "Afghanistan".into(),
        code: "AF".into(),
        coordinates: (66.0, 33.0),
    }; (c_af.code.clone(), c_af)},

    {let c_ag = Country {
        name: "Antigua and Barbuda".into(),
        code: "AG".into(),
        coordinates: (-61.85, 17.116666666),
    }; (c_ag.code.clone(), c_ag)},

    {let c_ai = Country {
        name: "Anguilla".into(),
        code: "AI".into(),
        coordinates: (43.16666667, 11.6),
    }; (c_ai.code.clone(), c_ai)},

    {let c_al = Country {
        name: "Albania".into(),
        code: "AL".into(),
        coordinates: (20.0, 41.0),
    }; (c_al.code.clone(), c_al)},

    {let c_am = Country {
        name: "Armenia".into(),
        code: "AM".into(),
        coordinates: (44.95, 40.383333),
    }; (c_am.code.clone(), c_am)},

    {let c_an = Country {
        name: "Netherlands Antilles".into(),
        code: "AN".into(),
        coordinates: (-66.0, 15.0),
    }; (c_an.code.clone(), c_an)},

    {let c_ao = Country {
        name: "Angola".into(),
        code: "AO".into(),
        coordinates: (17.35, -12.35),
    }; (c_ao.code.clone(), c_ao)},

    {let c_ap = Country {
        name: "Asia/Pacific".into(),
        code: "AP".into(),
        coordinates: (87.331111111, 43.681111111),
    }; (c_ap.code.clone(), c_ap)},

    {let c_aq = Country {
        name: "Antarctica".into(),
        code: "AQ".into(),
        coordinates: (0.0, -90.0),
    }; (c_aq.code.clone(), c_aq)},

    {let c_ar = Country {
        name: "Argentina".into(),
        code: "AR".into(),
        coordinates: (-64.0, -34.0),
    }; (c_ar.code.clone(), c_ar)},

    {let c_as = Country {
        name: "American Samoa".into(),
        code: "AS".into(),
        coordinates: (-170.7075, -14.295833),
    }; (c_as.code.clone(), c_as)},

    {let c_at = Country {
        name: "Austria".into(),
        code: "AT".into(),
        coordinates: (14.0, 48.0),
    }; (c_at.code.clone(), c_at)},

    {let c_au = Country {
        name: "Australia".into(),
        code: "AU".into(),
        coordinates: (133.0, -25.0),
    }; (c_au.code.clone(), c_au)},

    {let c_aw = Country {
        name: "Aruba".into(),
        code: "AW".into(),
        coordinates: (-69.97422388, 12.51106253),
    }; (c_aw.code.clone(), c_aw)},

    {let c_ax = Country {
        name: "Åland Islands".into(),
        code: "AX".into(),
        coordinates: (20.0, 60.25),
    }; (c_ax.code.clone(), c_ax)},

    {let c_az = Country {
        name: "Azerbaijan".into(),
        code: "AZ".into(),
        coordinates: (47.7, 40.3),
    }; (c_az.code.clone(), c_az)},

    {let c_ba = Country {
        name: "Bosnia and Herzegovina".into(),
        code: "BA".into(),
        coordinates: (18.0, 44.0),
    }; (c_ba.code.clone(), c_ba)},

    {let c_bb = Country {
        name: "Barbados".into(),
        code: "BB".into(),
        coordinates: (-59.5525, 13.17),
    }; (c_bb.code.clone(), c_bb)},

    {let c_bd = Country {
        name: "Bangladesh".into(),
        code: "BD".into(),
        coordinates: (89.866667, 24.016667),
    }; (c_bd.code.clone(), c_bd)},

    {let c_be = Country {
        name: "Belgium".into(),
        code: "BE".into(),
        coordinates: (4.668055555, 50.641111111),
    }; (c_be.code.clone(), c_be)},

    {let c_bf = Country {
        name: "Burkina Faso".into(),
        code: "BF".into(),
        coordinates: (-2.066667, 12.266667),
    }; (c_bf.code.clone(), c_bf)},

    {let c_bg = Country {
        name: "Bulgaria".into(),
        code: "BG".into(),
        coordinates: (25.5, 42.75),
    }; (c_bg.code.clone(), c_bg)},

    {let c_bh = Country {
        name: "Bahrain".into(),
        code: "BH".into(),
        coordinates: (50.551111, 26.0675),
    }; (c_bh.code.clone(), c_bh)},

    {let c_bi = Country {
        name: "Burundi".into(),
        code: "BI".into(),
        coordinates: (29.816667, -3.666667),
    }; (c_bi.code.clone(), c_bi)},

    {let c_bj = Country {
        name: "Benin".into(),
        code: "BJ".into(),
        coordinates: (2.183333333, 8.833333333),
    }; (c_bj.code.clone(), c_bj)},

    {let c_bl = Country {
        name: "Saint Barthélemy".into(),
        code: "BL".into(),
        coordinates: (-62.8342438, 17.897728),
    }; (c_bl.code.clone(), c_bl)},

    {let c_bm = Country {
        name: "Bermuda".into(),
        code: "BM".into(),
        coordinates: (-64.74, 32.32),
    }; (c_bm.code.clone(), c_bm)},

    {let c_bn = Country {
        name: "Brunei Darussalam".into(),
        code: "BN".into(),
        coordinates: (114.566667, 4.4),
    }; (c_bn.code.clone(), c_bn)},

    {let c_bo = Country {
        name: "Bolivia, Plurinational State of".into(),
        code: "BO".into(),
        coordinates: (-64.991228611, -17.056869611),
    }; (c_bo.code.clone(), c_bo)},

    {let c_bq = Country {
        name: "Bonaire, Sint Eustatius and Saba".into(),
        code: "BQ".into(),
        coordinates: (-50.0, -75.0),
    }; (c_bq.code.clone(), c_bq)},

    {let c_br = Country {
        name: "Brazil".into(),
        code: "BR".into(),
        coordinates: (-53.0, -14.0),
    }; (c_br.code.clone(), c_br)},

    {let c_bs = Country {
        name: "Bahamas".into(),
        code: "BS".into(),
        coordinates: (-77.4, 25.0),
    }; (c_bs.code.clone(), c_bs)},

    {let c_bt = Country {
        name: "Bhutan".into(),
        code: "BT".into(),
        coordinates: (90.5, 27.45),
    }; (c_bt.code.clone(), c_bt)},

    {let c_bv = Country {
        name: "Bouvet Island".into(),
        code: "BV".into(),
        coordinates: (3.36, -54.42),
    }; (c_bv.code.clone(), c_bv)},

    {let c_bw = Country {
        name: "Botswana".into(),
        code: "BW".into(),
        coordinates: (23.7, -22.2),
    }; (c_bw.code.clone(), c_bw)},

    {let c_by = Country {
        name: "Belarus".into(),
        code: "BY".into(),
        coordinates: (28.046666666, 53.528333333),
    }; (c_by.code.clone(), c_by)},

    {let c_bz = Country {
        name: "Belize".into(),
        code: "BZ".into(),
        coordinates: (-88.7, 17.066666666),
    }; (c_bz.code.clone(), c_bz)},

    {let c_ca = Country {
        name: "Canada".into(),
        code: "CA".into(),
        coordinates: (-109.0, 56.0),
    }; (c_ca.code.clone(), c_ca)},

    {let c_cc = Country {
        name: "Cocos (Keeling) Islands".into(),
        code: "CC".into(),
        coordinates: (96.895, -12.1175),
    }; (c_cc.code.clone(), c_cc)},

    {let c_cd = Country {
        name: "Congo, Democratic Republic of the".into(),
        code: "CD".into(),
        coordinates: (23.656111111, -2.88),
    }; (c_cd.code.clone(), c_cd)},

    {let c_cf = Country {
        name: "Central African Republic".into(),
        code: "CF".into(),
        coordinates: (20.9, 6.7),
    }; (c_cf.code.clone(), c_cf)},

    {let c_cg = Country {
        name: "Congo".into(),
        code: "CG".into(),
        coordinates: (15.383330555, -0.75),
    }; (c_cg.code.clone(), c_cg)},

    {let c_ch = Country {
        name: "Switzerland".into(),
        code: "CH".into(),
        coordinates: (8.231973, 46.798562),
    }; (c_ch.code.clone(), c_ch)},

    {let c_ci = Country {
        name: "Côte d'Ivoire".into(),
        code: "CI".into(),
        coordinates: (-6.0, 8.0),
    }; (c_ci.code.clone(), c_ci)},

    {let c_ck = Country {
        name: "Cook Islands".into(),
        code: "CK".into(),
        coordinates: (-159.783333333, -21.233333333),
    }; (c_ck.code.clone(), c_ck)},

    {let c_cl = Country {
        name: "Chile".into(),
        code: "CL".into(),
        coordinates: (-71.0, -33.0),
    }; (c_cl.code.clone(), c_cl)},

    {let c_cm = Country {
        name: "Cameroon".into(),
        code: "CM".into(),
        coordinates: (12.65, 5.133333333),
    }; (c_cm.code.clone(), c_cm)},

    {let c_cn = Country {
        name: "China".into(),
        code: "CN".into(),
        coordinates: (103.451944444, 35.844722222),
    }; (c_cn.code.clone(), c_cn)},

    {let c_co = Country {
        name: "Colombia".into(),
        code: "CO".into(),
        coordinates: (-73.25, 4.0),
    }; (c_co.code.clone(), c_co)},

    {let c_cr = Country {
        name: "Costa Rica".into(),
        code: "CR".into(),
        coordinates: (-84.0, 10.0),
    }; (c_cr.code.clone(), c_cr)},

    {let c_cs = Country {
        name: "Serbia and Montenegro".into(),
        code: "CS".into(),
        coordinates: (19.78, 43.15),
    }; (c_cs.code.clone(), c_cs)},

    {let c_cu = Country {
        name: "Cuba".into(),
        code: "CU".into(),
        coordinates: (-79.5, 22.0),
    }; (c_cu.code.clone(), c_cu)},

    {let c_cv = Country {
        name: "Cabo Verde".into(),
        code: "CV".into(),
        coordinates: (-23.7, 15.3),
    }; (c_cv.code.clone(), c_cv)},

    {let c_cw = Country {
        name: "Curaçao".into(),
        code: "CW".into(),
        coordinates: (-69.012, 12.1964),
    }; (c_cw.code.clone(), c_cw)},

    {let c_cx = Country {
        name: "Christmas Island".into(),
        code: "CX".into(),
        coordinates: (105.6275, -10.49),
    }; (c_cx.code.clone(), c_cx)},

    {let c_cy = Country {
        name: "Cyprus".into(),
        code: "CY".into(),
        coordinates: (33.0, 35.0),
    }; (c_cy.code.clone(), c_cy)},

    {let c_cz = Country {
        name: "Czechia".into(),
        code: "CZ".into(),
        coordinates: (15.0, 50.0),
    }; (c_cz.code.clone(), c_cz)},

    {let c_de = Country {
        name: "Germany".into(),
        code: "DE".into(),
        coordinates: (10.0, 51.0),
    }; (c_de.code.clone(), c_de)},

    {let c_dj = Country {
        name: "Djibouti".into(),
        code: "DJ".into(),
        coordinates: (42.433333, 11.8),
    }; (c_dj.code.clone(), c_dj)},

    {let c_dk = Country {
        name: "Denmark".into(),
        code: "DK".into(),
        coordinates: (10.0, 56.0),
    }; (c_dk.code.clone(), c_dk)},

    {let c_dm = Country {
        name: "Dominica".into(),
        code: "DM".into(),
        coordinates: (-61.333333, 15.416667),
    }; (c_dm.code.clone(), c_dm)},

    {let c_do = Country {
        name: "Dominican Republic".into(),
        code: "DO".into(),
        coordinates: (-70.2, 18.8),
    }; (c_do.code.clone(), c_do)},

    {let c_dz = Country {
        name: "Algeria".into(),
        code: "DZ".into(),
        coordinates: (1.0, 28.0),
    }; (c_dz.code.clone(), c_dz)},

    {let c_ec = Country {
        name: "Ecuador".into(),
        code: "EC".into(),
        coordinates: (-78.0, -1.0),
    }; (c_ec.code.clone(), c_ec)},

    {let c_ee = Country {
        name: "Estonia".into(),
        code: "EE".into(),
        coordinates: (26.0, 59.0),
    }; (c_ee.code.clone(), c_ee)},

    {let c_eg = Country {
        name: "Egypt".into(),
        code: "EG".into(),
        coordinates: (29.0, 27.0),
    }; (c_eg.code.clone(), c_eg)},

    {let c_eh = Country {
        name: "Western Sahara".into(),
        code: "EH".into(),
        coordinates: (-13.0, 25.0),
    }; (c_eh.code.clone(), c_eh)},

    {let c_er = Country {
        name: "Eritrea".into(),
        code: "ER".into(),
        coordinates: (38.25, 15.483333),
    }; (c_er.code.clone(), c_er)},

    {let c_es = Country {
        name: "Spain".into(),
        code: "ES".into(),
        coordinates: (-3.5, 40.2),
    }; (c_es.code.clone(), c_es)},

    {let c_et = Country {
        name: "Ethiopia".into(),
        code: "ET".into(),
        coordinates: (40.0, 9.0),
    }; (c_et.code.clone(), c_et)},

    {let c_eu = Country {
        name: "European Union".into(),
        code: "EU".into(),
        coordinates: (9.247777777, 50.116944444),
    }; (c_eu.code.clone(), c_eu)},

    {let c_fi = Country {
        name: "Finland".into(),
        code: "FI".into(),
        coordinates: (27.0, 65.0),
    }; (c_fi.code.clone(), c_fi)},

    {let c_fj = Country {
        name: "Fiji".into(),
        code: "FJ".into(),
        coordinates: (178.0, -18.0),
    }; (c_fj.code.clone(), c_fj)},

    {let c_fk = Country {
        name: "Falkland Islands (Malvinas)".into(),
        code: "FK".into(),
        coordinates: (-59.22, -51.73),
    }; (c_fk.code.clone(), c_fk)},

    {let c_fm = Country {
        name: "Micronesia, Federated States of".into(),
        code: "FM".into(),
        coordinates: (158.183333333, 6.916666666),
    }; (c_fm.code.clone(), c_fm)},

    {let c_fo = Country {
        name: "Faroe Islands".into(),
        code: "FO".into(),
        coordinates: (-6.844480555, 61.969944444),
    }; (c_fo.code.clone(), c_fo)},

    {let c_fr = Country {
        name: "France".into(),
        code: "FR".into(),
        coordinates: (2.0, 47.0),
    }; (c_fr.code.clone(), c_fr)},

    {let c_fx = Country {
        name: "France, Metropolitan".into(),
        code: "FX".into(),
        coordinates: (2.0, 46.0),
    }; (c_fx.code.clone(), c_fx)},

    {let c_ga = Country {
        name: "Gabon".into(),
        code: "GA".into(),
        coordinates: (11.5, -0.683330555),
    }; (c_ga.code.clone(), c_ga)},

    {let c_gb = Country {
        name: "United Kingdom of Great Britain and Northern Ireland".into(),
        code: "GB".into(),
        coordinates: (-2.0, 54.6),
    }; (c_gb.code.clone(), c_gb)},

    {let c_gd = Country {
        name: "Grenada".into(),
        code: "GD".into(),
        coordinates: (-61.666667, 12.116667),
    }; (c_gd.code.clone(), c_gd)},

    {let c_ge = Country {
        name: "Georgia".into(),
        code: "GE".into(),
        coordinates: (44.0, 42.0),
    }; (c_ge.code.clone(), c_ge)},

    {let c_gf = Country {
        name: "French Guiana".into(),
        code: "GF".into(),
        coordinates: (-52.99994, 3.99886),
    }; (c_gf.code.clone(), c_gf)},

    {let c_gg = Country {
        name: "Guernsey".into(),
        code: "GG".into(),
        coordinates: (-2.583333333, 49.45),
    }; (c_gg.code.clone(), c_gg)},

    {let c_gh = Country {
        name: "Ghana".into(),
        code: "GH".into(),
        coordinates: (-1.08, 8.03),
    }; (c_gh.code.clone(), c_gh)},

    {let c_gi = Country {
        name: "Gibraltar".into(),
        code: "GI".into(),
        coordinates: (-5.35, 36.14),
    }; (c_gi.code.clone(), c_gi)},

    {let c_gl = Country {
        name: "Greenland".into(),
        code: "GL".into(),
        coordinates: (-40.0, 72.0),
    }; (c_gl.code.clone(), c_gl)},

    {let c_gm = Country {
        name: "Gambia".into(),
        code: "GM".into(),
        coordinates: (-15.5, 13.5),
    }; (c_gm.code.clone(), c_gm)},

    {let c_gn = Country {
        name: "Guinea".into(),
        code: "GN".into(),
        coordinates: (-11.0, 10.0),
    }; (c_gn.code.clone(), c_gn)},

    {let c_gp = Country {
        name: "Guadeloupe".into(),
        code: "GP".into(),
        coordinates: (-61.5605, 16.2595),
    }; (c_gp.code.clone(), c_gp)},

    {let c_gq = Country {
        name: "Equatorial Guinea".into(),
        code: "GQ".into(),
        coordinates: (10.0, 1.5),
    }; (c_gq.code.clone(), c_gq)},

    {let c_gr = Country {
        name: "Greece".into(),
        code: "GR".into(),
        coordinates: (23.0, 38.5),
    }; (c_gr.code.clone(), c_gr)},

    {let c_gs = Country {
        name: "South Georgia and the South Sandwich Islands".into(),
        code: "GS".into(),
        coordinates: (-36.75, -54.25),
    }; (c_gs.code.clone(), c_gs)},

    {let c_gt = Country {
        name: "Guatemala".into(),
        code: "GT".into(),
        coordinates: (-90.25, 15.5),
    }; (c_gt.code.clone(), c_gt)},

    {let c_gu = Country {
        name: "Guam".into(),
        code: "GU".into(),
        coordinates: (144.8, 13.5),
    }; (c_gu.code.clone(), c_gu)},

    {let c_gw = Country {
        name: "Guinea-Bissau".into(),
        code: "GW".into(),
        coordinates: (-15.0, 12.0),
    }; (c_gw.code.clone(), c_gw)},

    {let c_gy = Country {
        name: "Guyana".into(),
        code: "GY".into(),
        coordinates: (-59.316667, 5.733333),
    }; (c_gy.code.clone(), c_gy)},

    {let c_hk = Country {
        name: "Hong Kong".into(),
        code: "HK".into(),
        coordinates: (114.158611111, 22.278333333),
    }; (c_hk.code.clone(), c_hk)},

    {let c_hm = Country {
        name: "Heard Island and McDonald Islands".into(),
        code: "HM".into(),
        coordinates: (73.517, -53.093527777),
    }; (c_hm.code.clone(), c_hm)},

    {let c_hn = Country {
        name: "Honduras".into(),
        code: "HN".into(),
        coordinates: (-86.816667, 14.633333),
    }; (c_hn.code.clone(), c_hn)},

    {let c_hr = Country {
        name: "Croatia".into(),
        code: "HR".into(),
        coordinates: (15.466667, 45.25),
    }; (c_hr.code.clone(), c_hr)},

    {let c_ht = Country {
        name: "Haiti".into(),
        code: "HT".into(),
        coordinates: (-72.8, 19.0),
    }; (c_ht.code.clone(), c_ht)},

    {let c_hu = Country {
        name: "Hungary".into(),
        code: "HU".into(),
        coordinates: (19.0, 47.0),
    }; (c_hu.code.clone(), c_hu)},

    {let c_id = Country {
        name: "Indonesia".into(),
        code: "ID".into(),
        coordinates: (118.0, -2.0),
    }; (c_id.code.clone(), c_id)},

    {let c_ie = Country {
        name: "Ireland".into(),
        code: "IE".into(),
        coordinates: (-8.0, 53.0),
    }; (c_ie.code.clone(), c_ie)},

    {let c_il = Country {
        name: "Israel".into(),
        code: "IL".into(),
        coordinates: (35.0, 31.0),
    }; (c_il.code.clone(), c_il)},

    {let c_im = Country {
        name: "Isle of Man".into(),
        code: "IM".into(),
        coordinates: (-4.525, 54.235),
    }; (c_im.code.clone(), c_im)},

    {let c_in = Country {
        name: "India".into(),
        code: "IN".into(),
        coordinates: (83.0, 22.8),
    }; (c_in.code.clone(), c_in)},

    {let c_io = Country {
        name: "British Indian Ocean Territory".into(),
        code: "IO".into(),
        coordinates: (71.5, -6.0),
    }; (c_io.code.clone(), c_io)},

    {let c_iq = Country {
        name: "Iraq".into(),
        code: "IQ".into(),
        coordinates: (43.0, 33.0),
    }; (c_iq.code.clone(), c_iq)},

    {let c_ir = Country {
        name: "Iran, Islamic Republic of".into(),
        code: "IR".into(),
        coordinates: (53.0, 32.0),
    }; (c_ir.code.clone(), c_ir)},

    {let c_is = Country {
        name: "Iceland".into(),
        code: "IS".into(),
        coordinates: (-19.0, 65.0),
    }; (c_is.code.clone(), c_is)},

    {let c_it = Country {
        name: "Italy".into(),
        code: "IT".into(),
        coordinates: (12.5, 42.5),
    }; (c_it.code.clone(), c_it)},

    {let c_je = Country {
        name: "Jersey".into(),
        code: "JE".into(),
        coordinates: (-2.11, 49.19),
    }; (c_je.code.clone(), c_je)},

    {let c_jm = Country {
        name: "Jamaica".into(),
        code: "JM".into(),
        coordinates: (-77.4, 18.18),
    }; (c_jm.code.clone(), c_jm)},

    {let c_jo = Country {
        name: "Jordan".into(),
        code: "JO".into(),
        coordinates: (36.5, 31.2),
    }; (c_jo.code.clone(), c_jo)},

    {let c_jp = Country {
        name: "Japan".into(),
        code: "JP".into(),
        coordinates: (136.0, 35.0),
    }; (c_jp.code.clone(), c_jp)},

    {let c_ke = Country {
        name: "Kenya".into(),
        code: "KE".into(),
        coordinates: (38.0, 0.1),
    }; (c_ke.code.clone(), c_ke)},

    {let c_kg = Country {
        name: "Kyrgyzstan".into(),
        code: "KG".into(),
        coordinates: (75.0, 41.0),
    }; (c_kg.code.clone(), c_kg)},

    {let c_kh = Country {
        name: "Cambodia".into(),
        code: "KH".into(),
        coordinates: (105.0, 12.5),
    }; (c_kh.code.clone(), c_kh)},

    {let c_ki = Country {
        name: "Kiribati".into(),
        code: "KI".into(),
        coordinates: (173.033333333, 1.466666666),
    }; (c_ki.code.clone(), c_ki)},

    {let c_km = Country {
        name: "Comoros".into(),
        code: "KM".into(),
        coordinates: (43.7, -12.3),
    }; (c_km.code.clone(), c_km)},

    {let c_kn = Country {
        name: "Saint Kitts and Nevis".into(),
        code: "KN".into(),
        coordinates: (-62.666669444, 17.271666666),
    }; (c_kn.code.clone(), c_kn)},

    {let c_kp = Country {
        name: "Korea, Democratic People's Republic of".into(),
        code: "KP".into(),
        coordinates: (127.0, 40.0),
    }; (c_kp.code.clone(), c_kp)},

    {let c_kr = Country {
        name: "Korea, Republic of".into(),
        code: "KR".into(),
        coordinates: (128.0, 36.0),
    }; (c_kr.code.clone(), c_kr)},

    {let c_kw = Country {
        name: "Kuwait".into(),
        code: "KW".into(),
        coordinates: (47.6, 29.166667),
    }; (c_kw.code.clone(), c_kw)},

    {let c_ky = Country {
        name: "Cayman Islands".into(),
        code: "KY".into(),
        coordinates: (-80.5, 19.5),
    }; (c_ky.code.clone(), c_ky)},

    {let c_kz = Country {
        name: "Kazakhstan".into(),
        code: "KZ".into(),
        coordinates: (68.0, 48.0),
    }; (c_kz.code.clone(), c_kz)},

    {let c_la = Country {
        name: "Lao People's Democratic Republic".into(),
        code: "LA".into(),
        coordinates: (104.1, 18.2),
    }; (c_la.code.clone(), c_la)},

    {let c_lb = Country {
        name: "Lebanon".into(),
        code: "LB".into(),
        coordinates: (35.766667, 33.833333),
    }; (c_lb.code.clone(), c_lb)},

    {let c_lc = Country {
        name: "Saint Lucia".into(),
        code: "LC".into(),
        coordinates: (-60.966666666, 13.883333333),
    }; (c_lc.code.clone(), c_lc)},

    {let c_li = Country {
        name: "Liechtenstein".into(),
        code: "LI".into(),
        coordinates: (9.553889, 47.145),
    }; (c_li.code.clone(), c_li)},

    {let c_lk = Country {
        name: "Sri Lanka".into(),
        code: "LK".into(),
        coordinates: (81.0, 7.0),
    }; (c_lk.code.clone(), c_lk)},

    {let c_lr = Country {
        name: "Liberia".into(),
        code: "LR".into(),
        coordinates: (-9.75, 6.533333),
    }; (c_lr.code.clone(), c_lr)},

    {let c_ls = Country {
        name: "Lesotho".into(),
        code: "LS".into(),
        coordinates: (28.25, -29.55),
    }; (c_ls.code.clone(), c_ls)},

    {let c_lt = Country {
        name: "Lithuania".into(),
        code: "LT".into(),
        coordinates: (24.0, 55.2),
    }; (c_lt.code.clone(), c_lt)},

    {let c_lu = Country {
        name: "Luxembourg".into(),
        code: "LU".into(),
        coordinates: (6.13, 49.77),
    }; (c_lu.code.clone(), c_lu)},

    {let c_lv = Country {
        name: "Latvia".into(),
        code: "LV".into(),
        coordinates: (25.0, 57.0),
    }; (c_lv.code.clone(), c_lv)},

    {let c_ly = Country {
        name: "Libya".into(),
        code: "LY".into(),
        coordinates: (17.0, 27.0),
    }; (c_ly.code.clone(), c_ly)},

    {let c_ma = Country {
        name: "Morocco".into(),
        code: "MA".into(),
        coordinates: (-6.0, 32.0),
    }; (c_ma.code.clone(), c_ma)},

    {let c_mc = Country {
        name: "Monaco".into(),
        code: "MC".into(),
        coordinates: (7.42, 43.731111111),
    }; (c_mc.code.clone(), c_mc)},

    {let c_md = Country {
        name: "Moldova, Republic of".into(),
        code: "MD".into(),
        coordinates: (28.516667, 47.25),
    }; (c_md.code.clone(), c_md)},

    {let c_me = Country {
        name: "Montenegro".into(),
        code: "ME".into(),
        coordinates: (19.216667, 42.766667),
    }; (c_me.code.clone(), c_me)},

    {let c_mf = Country {
        name: "Saint Martin (French part)".into(),
        code: "MF".into(),
        coordinates: (-63.06, 18.075277777),
    }; (c_mf.code.clone(), c_mf)},

    {let c_mg = Country {
        name: "Madagascar".into(),
        code: "MG".into(),
        coordinates: (47.0, -20.0),
    }; (c_mg.code.clone(), c_mg)},

    {let c_mh = Country {
        name: "Marshall Islands".into(),
        code: "MH".into(),
        coordinates: (169.29, 9.82),
    }; (c_mh.code.clone(), c_mh)},

    {let c_mk = Country {
        name: "Macedonia, the former Yugoslav Republic of".into(),
        code: "MK".into(),
        coordinates: (21.716667, 41.65),
    }; (c_mk.code.clone(), c_mk)},

    {let c_ml = Country {
        name: "Mali".into(),
        code: "ML".into(),
        coordinates: (-4.0, 17.0),
    }; (c_ml.code.clone(), c_ml)},

    {let c_mm = Country {
        name: "Myanmar".into(),
        code: "MM".into(),
        coordinates: (96.0, 22.0),
    }; (c_mm.code.clone(), c_mm)},

    {let c_mn = Country {
        name: "Mongolia".into(),
        code: "MN".into(),
        coordinates: (105.0, 46.0),
    }; (c_mn.code.clone(), c_mn)},

    {let c_mo = Country {
        name: "Macao".into(),
        code: "MO".into(),
        coordinates: (113.538055555, 22.19),
    }; (c_mo.code.clone(), c_mo)},

    {let c_mp = Country {
        name: "Northern Mariana Islands".into(),
        code: "MP".into(),
        coordinates: (145.78, 16.705),
    }; (c_mp.code.clone(), c_mp)},

    {let c_mq = Country {
        name: "Martinique".into(),
        code: "MQ".into(),
        coordinates: (-61.015, 14.65),
    }; (c_mq.code.clone(), c_mq)},

    {let c_mr = Country {
        name: "Mauritania".into(),
        code: "MR".into(),
        coordinates: (-11.0, 21.0),
    }; (c_mr.code.clone(), c_mr)},

    {let c_ms = Country {
        name: "Montserrat".into(),
        code: "MS".into(),
        coordinates: (-62.2, 16.75),
    }; (c_ms.code.clone(), c_ms)},

    {let c_mt = Country {
        name: "Malta".into(),
        code: "MT".into(),
        coordinates: (14.5, 35.883333333),
    }; (c_mt.code.clone(), c_mt)},

    {let c_mu = Country {
        name: "Mauritius".into(),
        code: "MU".into(),
        coordinates: (57.5, -20.2),
    }; (c_mu.code.clone(), c_mu)},

    {let c_mv = Country {
        name: "Maldives".into(),
        code: "MV".into(),
        coordinates: (73.51, 4.18),
    }; (c_mv.code.clone(), c_mv)},

    {let c_mw = Country {
        name: "Malawi".into(),
        code: "MW".into(),
        coordinates: (34.0, -13.0),
    }; (c_mw.code.clone(), c_mw)},

    {let c_mx = Country {
        name: "Mexico".into(),
        code: "MX".into(),
        coordinates: (-102.0, 23.0),
    }; (c_mx.code.clone(), c_mx)},

    {let c_my = Country {
        name: "Malaysia".into(),
        code: "MY".into(),
        coordinates: (102.314361666, 3.7805111),
    }; (c_my.code.clone(), c_my)},

    {let c_mz = Country {
        name: "Mozambique".into(),
        code: "MZ".into(),
        coordinates: (35.0, -19.0),
    }; (c_mz.code.clone(), c_mz)},

    {let c_na = Country {
        name: "Namibia".into(),
        code: "NA".into(),
        coordinates: (17.0, -23.0),
    }; (c_na.code.clone(), c_na)},

    {let c_nc = Country {
        name: "New Caledonia".into(),
        code: "NC".into(),
        coordinates: (165.3, -21.25),
    }; (c_nc.code.clone(), c_nc)},

    {let c_ne = Country {
        name: "Niger".into(),
        code: "NE".into(),
        coordinates: (10.0, 17.0),
    }; (c_ne.code.clone(), c_ne)},

    {let c_nf = Country {
        name: "Norfolk Island".into(),
        code: "NF".into(),
        coordinates: (167.949722222, -29.033333333),
    }; (c_nf.code.clone(), c_nf)},

    {let c_ng = Country {
        name: "Nigeria".into(),
        code: "NG".into(),
        coordinates: (8.0, 9.0),
    }; (c_ng.code.clone(), c_ng)},

    {let c_ni = Country {
        name: "Nicaragua".into(),
        code: "NI".into(),
        coordinates: (-85.0, 13.0),
    }; (c_ni.code.clone(), c_ni)},

    {let c_nl = Country {
        name: "Netherlands".into(),
        code: "NL".into(),
        coordinates: (5.55, 52.316666666),
    }; (c_nl.code.clone(), c_nl)},

    {let c_no = Country {
        name: "Norway".into(),
        code: "NO".into(),
        coordinates: (11.0, 65.0),
    }; (c_no.code.clone(), c_no)},

    {let c_np = Country {
        name: "Nepal".into(),
        code: "NP".into(),
        coordinates: (84.0, 28.0),
    }; (c_np.code.clone(), c_np)},

    {let c_nr = Country {
        name: "Nauru".into(),
        code: "NR".into(),
        coordinates: (166.935, -0.5275),
    }; (c_nr.code.clone(), c_nr)},

    {let c_nu = Country {
        name: "Niue".into(),
        code: "NU".into(),
        coordinates: (-169.916666666, -19.05),
    }; (c_nu.code.clone(), c_nu)},

    {let c_nz = Country {
        name: "New Zealand".into(),
        code: "NZ".into(),
        coordinates: (174.0, -41.2),
    }; (c_nz.code.clone(), c_nz)},

    {let c_om = Country {
        name: "Oman".into(),
        code: "OM".into(),
        coordinates: (57.0, 21.0),
    }; (c_om.code.clone(), c_om)},

    {let c_pa = Country {
        name: "Panama".into(),
        code: "PA".into(),
        coordinates: (-80.366667, 8.616667),
    }; (c_pa.code.clone(), c_pa)},

    {let c_pe = Country {
        name: "Peru".into(),
        code: "PE".into(),
        coordinates: (-76.0, -9.4),
    }; (c_pe.code.clone(), c_pe)},

    {let c_pf = Country {
        name: "French Polynesia".into(),
        code: "PF".into(),
        coordinates: (-149.566666666, -17.533333333),
    }; (c_pf.code.clone(), c_pf)},

    {let c_pg = Country {
        name: "Papua New Guinea".into(),
        code: "PG".into(),
        coordinates: (147.0, -6.3),
    }; (c_pg.code.clone(), c_pg)},

    {let c_ph = Country {
        name: "Philippines".into(),
        code: "PH".into(),
        coordinates: (123.0, 12.0),
    }; (c_ph.code.clone(), c_ph)},

    {let c_pk = Country {
        name: "Pakistan".into(),
        code: "PK".into(),
        coordinates: (71.0, 30.0),
    }; (c_pk.code.clone(), c_pk)},

    {let c_pl = Country {
        name: "Poland".into(),
        code: "PL".into(),
        coordinates: (19.0, 52.0),
    }; (c_pl.code.clone(), c_pl)},

    {let c_pm = Country {
        name: "Saint Pierre and Miquelon".into(),
        code: "PM".into(),
        coordinates: (-56.275, 46.825),
    }; (c_pm.code.clone(), c_pm)},

    {let c_pn = Country {
        name: "Pitcairn".into(),
        code: "PN".into(),
        coordinates: (-130.1045778, -25.0677812),
    }; (c_pn.code.clone(), c_pn)},

    {let c_pr = Country {
        name: "Puerto Rico".into(),
        code: "PR".into(),
        coordinates: (-66.5, 18.25),
    }; (c_pr.code.clone(), c_pr)},

    {let c_ps = Country {
        name: "Palestine".into(),
        code: "PS".into(),
        coordinates: (35.25, 32.0),
    }; (c_ps.code.clone(), c_ps)},

    {let c_pt = Country {
        name: "Portugal".into(),
        code: "PT".into(),
        coordinates: (-9.183333333, 38.7),
    }; (c_pt.code.clone(), c_pt)},

    {let c_pw = Country {
        name: "Palau".into(),
        code: "PW".into(),
        coordinates: (134.55, 7.466667),
    }; (c_pw.code.clone(), c_pw)},

    {let c_py = Country {
        name: "Paraguay".into(),
        code: "PY".into(),
        coordinates: (-58.0, -23.5),
    }; (c_py.code.clone(), c_py)},

    {let c_qa = Country {
        name: "Qatar".into(),
        code: "QA".into(),
        coordinates: (51.212767, 25.269535),
    }; (c_qa.code.clone(), c_qa)},

    {let c_re = Country {
        name: "Réunion".into(),
        code: "RE".into(),
        coordinates: (55.5325, -21.114444444),
    }; (c_re.code.clone(), c_re)},

    {let c_ro = Country {
        name: "Romania".into(),
        code: "RO".into(),
        coordinates: (25.0, 46.0),
    }; (c_ro.code.clone(), c_ro)},

    {let c_rs = Country {
        name: "Serbia".into(),
        code: "RS".into(),
        coordinates: (20.933333333, 43.95),
    }; (c_rs.code.clone(), c_rs)},

    {let c_ru = Country {
        name: "Russian Federation".into(),
        code: "RU".into(),
        coordinates: (94.25, 66.416666666),
    }; (c_ru.code.clone(), c_ru)},

    {let c_rw = Country {
        name: "Rwanda".into(),
        code: "RW".into(),
        coordinates: (30.0, -2.0),
    }; (c_rw.code.clone(), c_rw)},

    {let c_sa = Country {
        name: "Saudi Arabia".into(),
        code: "SA".into(),
        coordinates: (44.116667, 23.716667),
    }; (c_sa.code.clone(), c_sa)},

    {let c_sb = Country {
        name: "Solomon Islands".into(),
        code: "SB".into(),
        coordinates: (159.816666666, -9.466666666),
    }; (c_sb.code.clone(), c_sb)},

    {let c_sc = Country {
        name: "Seychelles".into(),
        code: "SC".into(),
        coordinates: (52.766667, -7.1),
    }; (c_sc.code.clone(), c_sc)},

    {let c_sd = Country {
        name: "Sudan".into(),
        code: "SD".into(),
        coordinates: (32.0, 15.0),
    }; (c_sd.code.clone(), c_sd)},

    {let c_se = Country {
        name: "Sweden".into(),
        code: "SE".into(),
        coordinates: (15.0, 61.0),
    }; (c_se.code.clone(), c_se)},

    {let c_sg = Country {
        name: "Singapore".into(),
        code: "SG".into(),
        coordinates: (103.8, 1.3),
    }; (c_sg.code.clone(), c_sg)},

    {let c_sh = Country {
        name: "Saint Helena, Ascension and Tristan da Cunha".into(),
        code: "SH".into(),
        coordinates: (-5.7181, -15.9245),
    }; (c_sh.code.clone(), c_sh)},

    {let c_si = Country {
        name: "Slovenia".into(),
        code: "SI".into(),
        coordinates: (15.0, 46.0),
    }; (c_si.code.clone(), c_si)},

    {let c_sj = Country {
        name: "Svalbard and Jan Mayen".into(),
        code: "SJ".into(),
        coordinates: (21.9939078, 78.6351661),
    }; (c_sj.code.clone(), c_sj)},

    {let c_sk = Country {
        name: "Slovakia".into(),
        code: "SK".into(),
        coordinates: (20.0, 49.0),
    }; (c_sk.code.clone(), c_sk)},

    {let c_sl = Country {
        name: "Sierra Leone".into(),
        code: "SL".into(),
        coordinates: (-12.1, 8.5),
    }; (c_sl.code.clone(), c_sl)},

    {let c_sm = Country {
        name: "San Marino".into(),
        code: "SM".into(),
        coordinates: (12.466666666, 43.933333333),
    }; (c_sm.code.clone(), c_sm)},

    {let c_sn = Country {
        name: "Senegal".into(),
        code: "SN".into(),
        coordinates: (-14.283333, 14.366667),
    }; (c_sn.code.clone(), c_sn)},

    {let c_so = Country {
        name: "Somalia".into(),
        code: "SO".into(),
        coordinates: (47.0, 6.0),
    }; (c_so.code.clone(), c_so)},

    {let c_sr = Country {
        name: "Suriname".into(),
        code: "SR".into(),
        coordinates: (-56.0, 4.0),
    }; (c_sr.code.clone(), c_sr)},

    {let c_ss = Country {
        name: "South Sudan".into(),
        code: "SS".into(),
        coordinates: (30.0, 7.0),
    }; (c_ss.code.clone(), c_ss)},

    {let c_st = Country {
        name: "Sao Tome and Principe".into(),
        code: "ST".into(),
        coordinates: (6.6, 0.316667),
    }; (c_st.code.clone(), c_st)},

    {let c_sv = Country {
        name: "El Salvador".into(),
        code: "SV".into(),
        coordinates: (-88.866111, 13.668889),
    }; (c_sv.code.clone(), c_sv)},

    {let c_sx = Country {
        name: "Sint Maarten (Dutch part)".into(),
        code: "SX".into(),
        coordinates: (-63.067777777, 18.031944444),
    }; (c_sx.code.clone(), c_sx)},

    {let c_sy = Country {
        name: "Syrian Arab Republic".into(),
        code: "SY".into(),
        coordinates: (38.583333, 35.216667),
    }; (c_sy.code.clone(), c_sy)},

    {let c_sz = Country {
        name: "Swaziland".into(),
        code: "SZ".into(),
        coordinates: (31.433333, -26.483333),
    }; (c_sz.code.clone(), c_sz)},

    {let c_tc = Country {
        name: "Turks and Caicos Islands".into(),
        code: "TC".into(),
        coordinates: (-71.8, 21.78),
    }; (c_tc.code.clone(), c_tc)},

    {let c_td = Country {
        name: "Chad".into(),
        code: "TD".into(),
        coordinates: (19.4, 15.466667),
    }; (c_td.code.clone(), c_td)},

    {let c_tf = Country {
        name: "French Southern Territories".into(),
        code: "TF".into(),
        coordinates: (67.0, -43.0),
    }; (c_tf.code.clone(), c_tf)},

    {let c_tg = Country {
        name: "Togo".into(),
        code: "TG".into(),
        coordinates: (1.183333, 8.25),
    }; (c_tg.code.clone(), c_tg)},

    {let c_th = Country {
        name: "Thailand".into(),
        code: "TH".into(),
        coordinates: (101.0, 14.0),
    }; (c_th.code.clone(), c_th)},

    {let c_tj = Country {
        name: "Tajikistan".into(),
        code: "TJ".into(),
        coordinates: (71.366667, 38.583333),
    }; (c_tj.code.clone(), c_tj)},

    {let c_tk = Country {
        name: "Tokelau".into(),
        code: "TK".into(),
        coordinates: (-171.833333333, -9.166666666),
    }; (c_tk.code.clone(), c_tk)},

    {let c_tl = Country {
        name: "Timor-Leste".into(),
        code: "TL".into(),
        coordinates: (125.75, -8.966667),
    }; (c_tl.code.clone(), c_tl)},

    {let c_tm = Country {
        name: "Turkmenistan".into(),
        code: "TM".into(),
        coordinates: (60.0, 39.0),
    }; (c_tm.code.clone(), c_tm)},

    {let c_tn = Country {
        name: "Tunisia".into(),
        code: "TN".into(),
        coordinates: (10.0, 34.0),
    }; (c_tn.code.clone(), c_tn)},

    {let c_to = Country {
        name: "Tonga".into(),
        code: "TO".into(),
        coordinates: (-174.810278, -20.587778),
    }; (c_to.code.clone(), c_to)},

    {let c_tr = Country {
        name: "Turkey".into(),
        code: "TR".into(),
        coordinates: (36.0, 39.0),
    }; (c_tr.code.clone(), c_tr)},

    {let c_tt = Country {
        name: "Trinidad and Tobago".into(),
        code: "TT".into(),
        coordinates: (-61.516666666, 10.666666666),
    }; (c_tt.code.clone(), c_tt)},

    {let c_tv = Country {
        name: "Tuvalu".into(),
        code: "TV".into(),
        coordinates: (178.005556, -7.475),
    }; (c_tv.code.clone(), c_tv)},

    {let c_tw = Country {
        name: "Taiwan".into(),
        code: "TW".into(),
        coordinates: (121.0, 24.0),
    }; (c_tw.code.clone(), c_tw)},

    {let c_tz = Country {
        name: "Tanzania, United Republic of".into(),
        code: "TZ".into(),
        coordinates: (34.853888888, -6.306944444),
    }; (c_tz.code.clone(), c_tz)},

    {let c_ua = Country {
        name: "Ukraine".into(),
        code: "UA".into(),
        coordinates: (32.0, 49.0),
    }; (c_ua.code.clone(), c_ua)},

    {let c_ug = Country {
        name: "Uganda".into(),
        code: "UG".into(),
        coordinates: (32.39, 1.28),
    }; (c_ug.code.clone(), c_ug)},

    {let c_um = Country {
        name: "United States Minor Outlying Islands".into(),
        code: "UM".into(),
        coordinates: (166.633333, 19.3),
    }; (c_um.code.clone(), c_um)},

    {let c_us = Country {
        name: "United States of America".into(),
        code: "US".into(),
        coordinates: (-98.5795, 39.828175),
    }; (c_us.code.clone(), c_us)},

    {let c_uy = Country {
        name: "Uruguay".into(),
        code: "UY".into(),
        coordinates: (-56.0, -33.0),
    }; (c_uy.code.clone(), c_uy)},

    {let c_uz = Country {
        name: "Uzbekistan".into(),
        code: "UZ".into(),
        coordinates: (66.0, 41.0),
    }; (c_uz.code.clone(), c_uz)},

    {let c_va = Country {
        name: "Holy See".into(),
        code: "VA".into(),
        coordinates: (12.453, 41.904),
    }; (c_va.code.clone(), c_va)},

    {let c_vc = Country {
        name: "Saint Vincent and the Grenadines".into(),
        code: "VC".into(),
        coordinates: (-61.2296, 13.0139),
    }; (c_vc.code.clone(), c_vc)},

    {let c_ve = Country {
        name: "Venezuela, Bolivarian Republic of".into(),
        code: "VE".into(),
        coordinates: (-67.0, 8.0),
    }; (c_ve.code.clone(), c_ve)},

    {let c_vg = Country {
        name: "Virgin Islands, British".into(),
        code: "VG".into(),
        coordinates: (-64.54, 18.445),
    }; (c_vg.code.clone(), c_vg)},

    {let c_vi = Country {
        name: "Virgin Islands, U.S.".into(),
        code: "VI".into(),
        coordinates: (-64.833333, 18.333333),
    }; (c_vi.code.clone(), c_vi)},

    {let c_vn = Country {
        name: "Viet Nam".into(),
        code: "VN".into(),
        coordinates: (108.0, 16.0),
    }; (c_vn.code.clone(), c_vn)},

    {let c_vu = Country {
        name: "Vanuatu".into(),
        code: "VU".into(),
        coordinates: (168.016669444, -16.633330555),
    }; (c_vu.code.clone(), c_vu)},

    {let c_wf = Country {
        name: "Wallis and Futuna".into(),
        code: "WF".into(),
        coordinates: (-178.10932, -14.30181),
    }; (c_wf.code.clone(), c_wf)},

    {let c_ws = Country {
        name: "Samoa".into(),
        code: "WS".into(),
        coordinates: (-172.2175, -13.745),
    }; (c_ws.code.clone(), c_ws)},

    {let c_ye = Country {
        name: "Yemen".into(),
        code: "YE".into(),
        coordinates: (48.0, 15.5),
    }; (c_ye.code.clone(), c_ye)},

    {let c_yt = Country {
        name: "Mayotte".into(),
        code: "YT".into(),
        coordinates: (45.138333333, -12.843055555),
    }; (c_yt.code.clone(), c_yt)},

    {let c_za = Country {
        name: "South Africa".into(),
        code: "ZA".into(),
        coordinates: (24.0, -29.0),
    }; (c_za.code.clone(), c_za)},

    {let c_zm = Country {
        name: "Zambia".into(),
        code: "ZM".into(),
        coordinates: (28.0, -14.0),
    }; (c_zm.code.clone(), c_zm)},

    {let c_zw = Country {
        name: "Zimbabwe".into(),
        code: "ZW".into(),
        coordinates: (30.0, -19.0),
    }; (c_zw.code.clone(), c_zw)},

    {let unknown = Country {
        name: "Unknown".into(),
        code: "??".into(),
        coordinates: (0.0, 0.0),
    }; (unknown.code.clone(), unknown)},
])}
